version: "3.3"

services:

  db:
    container_name: mysql_libr
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
    networks:
      - rede_node_express

  dockernodeapi:
    container_name: node-express-biblioteca
    build: ./api
    ports: 
      - "3000:3000"
    volumes:
      - ./api:/usr/app
    networks:
      - rede_node_express
    depends_on:
      - db
      
  dockernodefront:
    container_name: node-react-biblioteca
    build: ./front
    ports:
      - "8000:8000"
    volumes:
      - ./front:/usr/app
    networks:
      - rede_node_express

volumes:
  mysql-db:

networks:
  rede_node_express:
    driver: bridge